ruby_stuffs/rails_microposts/config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
end

ruby_stuffs/rails_microposts/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby_stuffs/rails_microposts/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :name,
    presence: true,
    length: { minimum: 4, maximum: 50 }

  validates :email,
    presence: true,
    length: { maximum: 255 },
    format: { with: URI::MailTo::EMAIL_REGEXP }, # Not a 100% compliant regex but good enough for most purposes
    uniqueness: { case_sensitive: false }

  validates :password,
    length: { minimum: 8 }
end

ruby_stuffs/rails_microposts/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

ruby_stuffs/rails_microposts/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user != nil && user.authenticate(params[:session][:password])
      # Login success
      log_in user
      redirect_to user
    else
      # Login fail
      flash.now[:danger] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
  end
end

ruby_stuffs/rails_microposts/app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
  def help; end
  def about; end
  def contact; end
end

ruby_stuffs/rails_microposts/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to microposts!"
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
    )
  end
end

ruby_stuffs/rails_microposts/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Returns what should go in a <title> for a page
  def full_title(page_title = "")
    base_title = "Microposts"

    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

ruby_stuffs/rails_microposts/app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if !session[:user_id].nil?
      @current_user ||= User.find_by(id: session[:user_id])
    else
      nil
    end
  end

  def logged_in?
    !session[:user_id].nil?
  end
end

ruby_stuffs/rails_microposts/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

ruby_stuffs/rails_microposts/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Returns an gravatar image tag for a user
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=identicon&s=#{size}"

    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

ruby_stuffs/rails_microposts/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Woah, here's some teensy text! owo
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

ruby_stuffs/rails_microposts/app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container center">
    <%= link_to "Microposts", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="navbar-nav">
        <li><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li><%= link_to "Help", help_path, class: "nav-link" %></li>

        <% if logged_in? %>
          <li><%= link_to "Users", "#", class: "nav-link" %></li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Settings", "#", class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

ruby_stuffs/rails_microposts/app/views/layouts/_shims.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

ruby_stuffs/rails_microposts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

    <%= render "layouts/shims" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container main-container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>

      <%= yield %>

      <%= render "layouts/footer" %>

      <% if Rails.env.development? %>
        <div class="container bg-dark text-light rounded">
          <%= debug(params) %>
        </div>
      <% end %>
    </div>
  </body>
</html>

ruby_stuffs/rails_microposts/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error-explanation">
    <div class="alert alert-danger", role="alert">
      <% @user.errors.full_messages.each do |msg| %>
        <ul><%= msg %></ul>
      <% end %>
    </div>
  </div>
<% end %>

ruby_stuffs/rails_microposts/app/views/static_pages/about.html.erb
<% provide :title, "About" %>
<h1>About</h1>
<p>Woah here's some microposts or something I guess</p>

ruby_stuffs/rails_microposts/app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>
<h1>Contact</h1>
<p>
  Contact us..somewhere, I guess...
</p>

ruby_stuffs/rails_microposts/app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>Help</h1>
<p>Oh nyoooooooooooooooooo &gt;.&lt;</p>

ruby_stuffs/rails_microposts/app/views/static_pages/home.html.erb
<div class="center bg-light p-5 m-3 rounded">
  <h1 class="display-4">Micropoooooooooooosts</h1>
  <h2 class="lead">This is the home page for Micropoooooooooooosts owo</h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails-logo.svg", alt: "Rails logo", width: 200), "https://rubyonrails.com" %>

ruby_stuffs/rails_microposts/app/views/users/new.html.erb
<% provide :title, "Sign up" %>

<div class="login-box">
  <h1 class="text-center">Sign up</h1>
  <%= render "shared/error_messages" %>

  <%= form_with model: @user, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :email, class: "form-label" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :password, class: "form-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :password_confirmation, class: "form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Create account", class: "btn btn-primary w-100" %>
  <% end %>
</div>

ruby_stuffs/rails_microposts/app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <aside class="col-sm-3">
      <section>
        <%= gravatar_for @user, size: 85 %>
        <h1 class="align-middle"><%= @user.name %></h1>
        <small><%= @user.id %></small>
      </section>
      <section>
        <p>Joined <%= @user.created_at %></p>
      </section>
    </aside>

    <div class="col-sm-9">
      <p>woah</p>
    </div>
  </div>
</div>