ruby_stuffs/rails_polls/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :polls
  get "/", to: "polls#index", as: "polls"
  post "/", to: "polls#create"

  get "/new", to: "polls#new", as: "new_poll"
  get "/:id", to: "polls#show", as: "poll"

  post "/vote/:option_id", to: "polls#vote", as: "vote_poll_option"
end

ruby_stuffs/rails_polls/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby_stuffs/rails_polls/app/models/poll.rb
# frozen_string_literal: true

class Poll < ApplicationRecord
  has_many :poll_options, dependent: :destroy
  validates_associated :poll_options
  accepts_nested_attributes_for :poll_options

  validates :question, presence: true
end

ruby_stuffs/rails_polls/app/models/poll_option.rb
# frozen_string_literal: true

class PollOption < ApplicationRecord
  belongs_to :poll
  validates :option, presence: true
end

ruby_stuffs/rails_polls/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

ruby_stuffs/rails_polls/app/controllers/polls_controller.rb
# frozen_string_literal: true

class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
    3.times do
      @poll.poll_options.build
    end
  end

  def create
    poll = Poll.new(poll_params)

    if poll.save
      redirect_to poll, notice: "Poll was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def vote
    option = PollOption.find(params[:option_id])
    option.votes += 1
    option.save!

    redirect_to poll_url(option.poll_id)
  end

  private

  def poll_params
    params.require(:poll).permit(:question, poll_options_attributes: [:option])
  end
end

ruby_stuffs/rails_polls/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_stuffs/rails_polls/app/helpers/poll_helper.rb
module PollHelper
end

ruby_stuffs/rails_polls/app/views/polls/index.html.erb
<h1>Polls!</h1>

<ul>
  <% @polls.each do |poll| %>
    <li><%= link_to poll.question, poll %></li>
  <% end %>

  <%= link_to "Make a new poll", new_poll_path %>
</ul>

ruby_stuffs/rails_polls/app/views/polls/new.html.erb
<h1>New poll</h1>

<%= form_for @poll do |form| %>
  <%= form.label :question, "Question" %>
  <%= form.text_field :question %>

  <%= form.fields_for :poll_options do |child_fields| %>
    <%= child_fields.label :option, "Option" %>
    <%= child_fields.text_field :option %>
  <% end %>

  <%= form.submit "Create" %>
<% end %>

ruby_stuffs/rails_polls/app/views/polls/show.html.erb
<h1><%= @poll.question %></h1>
<ul>
  <% @poll.poll_options.each do |opt| %>
    <li>
      <h3><%= opt.option %></h3>
      <p><%= opt.votes %> votes</p>
      <%= form_for :vote, url: vote_poll_option_path(opt.id) do |form| %>
        <%= form.submit "Vote" %>
      <% end %>
    </li>
  <% end %>
</ul>